from enum import Enum


class KlineStreamReturnData(Enum):
    EVENT_TYPE = 'EVENT_TYPE'
    EVENT_TIME = 'EVENT_TIME'
    SYMBOL = 'SYMBOL'
    START_TIME = 'START_TIME'
    CLOSE_TIME = 'CLOSE_TIME'
    INTERVAL = 'INTERVAL'
    FIRST_TRADE_ID = 'FIRST_TRADE_ID'
    LAST_TRADE_ID = 'LAST_TRADE_ID'
    OPEN_PRICE = 'OPEN_PRICE'
    CLOSE_PRICE = 'CLOSE_PRICE'
    HIGH_PRICE = 'HIGH_PRICE'
    LOW_PRICE = 'LOW_PRICE'
    BASE_ASSET_VOLUME = 'BASE_ASSET_VOLUME'
    NUMBER_OF_TRADES = 'NUMBER_OF_TRADES'
    IS_CLOSED = 'IS_CLOSED'
    QUOTE_ASSET_VOLUME = 'QUOTE_ASSET_VOLUME'
    TAKER_BUY_BASE_ASSET_VOLUME = 'TAKER_BUY_BASE_ASSET_VOLUME'
    TAKER_BUY_QUOTE_ASSET_VOLUME = 'TAKER_BUY_QUOTE_ASSET_VOLUME'
